use crate::family::SetFamily;
use rayon::prelude::*;
use std::collections::HashSet;

/// Generate all union-closed families on universe `m` by exhaustive power-set search (feasible for m <= 4).
pub fn generate_all_exhaustive(m: usize) -> Vec<SetFamily> {
    assert!(m <= 4, "Exhaustive generation only supported for m <= 4");
    let num_sets = 1usize << m;
    let total_families = 1usize << num_sets;

    (0..total_families)
        .into_par_iter()
        .filter_map(|mask| {
            // Reconstruct family sets from bitmask
            let mut sets = Vec::new();
            for s in 0..num_sets {
                if (mask & (1 << s)) != 0 {
                    sets.push(s as u64);
                }
            }

            let family = SetFamily::new(m, sets);
            if family.is_union_closed() {
                Some(family)
            } else {
                None
            }
        })
        .collect()
}

/// Generate union-closed families on universe `m` generated by all subsets of basis size `k` (k <= 6).
pub fn generate_by_basis_size(m: usize, k: usize, include_empty: bool) -> Vec<SetFamily> {
    let num_nonempty_sets = (1usize << m) - 1;
    let mut candidate_sets: Vec<u64> = (1..=num_nonempty_sets).map(|s| s as u64).collect();
    // Sort candidate sets
    candidate_sets.sort_unstable();

    // Generate combinations of size k from candidate_sets
    let mut combinations = Vec::new();
    let n_cands = candidate_sets.len();

    fn combine(
        start: usize,
        k: usize,
        n: usize,
        cands: &[u64],
        current: &mut Vec<u64>,
        combos: &mut Vec<Vec<u64>>,
    ) {
        if current.len() == k {
            combos.push(current.clone());
            return;
        }
        for i in start..n {
            current.push(cands[i]);
            combine(i + 1, k, n, cands, current, combos);
            current.pop();
        }
    }

    let mut cur = Vec::new();
    combine(0, k, n_cands, &candidate_sets, &mut cur, &mut combinations);

    // Parallel closure generation and deduplication
    let families: Vec<SetFamily> = combinations
        .par_iter()
        .map(|basis| SetFamily::from_generators(m, basis, include_empty))
        .collect();

    // Deduplicate canonically
    let mut unique_canonical = HashSet::new();
    let mut deduped = Vec::new();

    for f in families {
        let canon = f.canonical_form();
        if unique_canonical.insert(canon.sets.clone()) {
            deduped.push(f);
        }
    }

    deduped
}

/// Generate all canonical union-closed families on universe `m` for all basis sizes 1..=max_k.
pub fn generate_canonical_basis_frontier(
    m: usize,
    max_k: usize,
    include_empty: bool,
) -> Vec<SetFamily> {
    let mut all_families = Vec::new();
    for k in 1..=max_k {
        let families_k = generate_by_basis_size(m, k, include_empty);
        all_families.extend(families_k);
    }

    // Global canonical deduplication
    let mut unique = HashSet::new();
    let mut result = Vec::new();

    for f in all_families {
        let canon = f.canonical_form();
        if unique.insert(canon.sets.clone()) {
            result.push(canon);
        }
    }

    result
}
