use crate::family::Family;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratorSearchResult {
    pub k_generators: usize,
    pub ground_set_size: usize,
    pub total_tested: usize,
    pub min_frankl_ratio: f64,
    pub min_ratio_fraction: String,
    pub extremal_count: usize,
    pub counterexamples: usize,
}

/// Stress test families generated by k generators (k = 3, 4, 5, 6) across random and structured configurations.
pub fn search_k_generator_families(k: usize, m: usize, num_samples: usize) -> GeneratorSearchResult {
    use std::sync::atomic::{AtomicUsize, Ordering};

    let total_tested = AtomicUsize::new(0);
    let counterexamples = AtomicUsize::new(0);
    let extremal_count = AtomicUsize::new(0);
    let min_ratio_bits = std::sync::Mutex::new((1.0f64, 1usize, 2usize));

    // Sample random bases of size k from 2^[m]
    // Use chunks in parallel
    let chunk_size = 1000;
    let num_chunks = (num_samples + chunk_size - 1) / chunk_size;

    (0..num_chunks).into_par_iter().for_each(|chunk_idx| {
        let mut rng_state = 123456789u64 ^ ((chunk_idx as u64) * 0x9E3779B97F4A7C15);
        let mut local_tested = 0;
        let mut local_counterexamples = 0;
        let mut local_extremal = 0;
        let mut local_min = 1.0f64;
        let mut local_num = 1;
        let mut local_den = 1;

        let end = ((chunk_idx + 1) * chunk_size).min(num_samples);
        for _ in (chunk_idx * chunk_size)..end {
            // Generate k random non-empty subsets of [m]
            let mut gens = Vec::with_capacity(k);
            let mut full_union = 0u32;
            for _ in 0..k {
                rng_state = rng_state.wrapping_mul(6364136223846793005).wrapping_add(1);
                let mask = ((rng_state >> 32) as u32) & ((1u32 << m) - 1);
                let s = if mask == 0 { 1u32 << (rng_state % (m as u64)) } else { mask };
                gens.push(s);
                full_union |= s;
            }

            // Ground set size is count of active bits
            let active_elements = full_union.count_ones() as usize;
            if active_elements < 2 {
                continue;
            }

            let fam = Family::from_generators(m, &gens);
            if fam.sets.len() < 2 {
                continue;
            }

            local_tested += 1;
            let (max_deg, _) = fam.max_degree();
            let size = fam.sets.len();
            let ratio = max_deg as f64 / size as f64;

            if ratio < local_min {
                local_min = ratio;
                local_num = max_deg;
                local_den = size;
            }

            if 2 * max_deg < size {
                local_counterexamples += 1;
            } else if 2 * max_deg == size {
                local_extremal += 1;
            }
        }

        total_tested.fetch_add(local_tested, Ordering::Relaxed);
        counterexamples.fetch_add(local_counterexamples, Ordering::Relaxed);
        extremal_count.fetch_add(local_extremal, Ordering::Relaxed);

        let mut global_min = min_ratio_bits.lock().unwrap();
        if local_min < global_min.0 {
            *global_min = (local_min, local_num, local_den);
        }
    });

    let best_min = min_ratio_bits.into_inner().unwrap();

    GeneratorSearchResult {
        k_generators: k,
        ground_set_size: m,
        total_tested: total_tested.load(Ordering::Relaxed),
        min_frankl_ratio: best_min.0,
        min_ratio_fraction: format!("{}/{}", best_min.1, best_min.2),
        extremal_count: extremal_count.load(Ordering::Relaxed),
        counterexamples: counterexamples.load(Ordering::Relaxed),
    }
}
