#!/usr/bin/env python3
"""
Independent Standalone Verifier for 1/3-2/3 Poset Conjecture Computations.

This script implements an entirely independent algorithm (pure Python recursive DFS topological sort)
to cross-check poset validity, linear extension counts, and pair balance metrics against the data
generated by the Rust poset_engine.
"""

import sys
import json
from pathlib import Path
from fractions import Fraction


def verify_partial_order(n: int, matrix: list[list[int]]) -> bool:
    """Check irreflexivity, asymmetry, and transitivity of strict partial order matrix."""
    # Irreflexive
    for i in range(n):
        if matrix[i][i] != 0:
            return False
    # Asymmetric
    for i in range(n):
        for j in range(n):
            if matrix[i][j] == 1 and matrix[j][i] == 1:
                return False
    # Transitive
    for i in range(n):
        for j in range(n):
            if matrix[i][j] == 1:
                for k in range(n):
                    if matrix[j][k] == 1 and matrix[i][k] != 1:
                        return False
    return True


def count_linear_extensions_python(n: int, matrix: list[list[int]]) -> tuple[int, dict[tuple[int, int], int]]:
    """
    Independent linear extension enumerator using recursive backtracking.
    Returns (total_extensions, pair_counts_dict) where pair_counts_dict[(u, v)] = e(u < v).
    """
    in_degrees = [0] * n
    for j in range(n):
        for i in range(n):
            if matrix[i][j] == 1:
                in_degrees[j] += 1

    pair_counts = {(u, v): 0 for u in range(n) for v in range(n) if u != v}
    total = [0]
    current_seq = [0] * n
    chosen_mask = 0

    def dfs(step: int, mask: int):
        if step == n:
            total[0] += 1
            for i in range(n):
                u = current_seq[i]
                for j in range(i + 1, n):
                    v = current_seq[j]
                    pair_counts[(u, v)] += 1
            return

        for v in range(n):
            if (mask & (1 << v)) == 0 and in_degrees[v] == 0:
                current_seq[step] = v
                for succ in range(n):
                    if matrix[v][succ] == 1:
                        in_degrees[succ] -= 1

                dfs(step + 1, mask | (1 << v))

                for succ in range(n):
                    if matrix[v][succ] == 1:
                        in_degrees[succ] += 1

    dfs(0, chosen_mask)
    return total[0], pair_counts


def audit_extremal_posets(json_path: Path):
    print(f"Loading artifact from {json_path}...")
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    extremal_posets = data["extremal_posets"]
    print(f"Auditing {len(extremal_posets)} strictly extremal posets (delta = 1/3)...")

    for i, rec in enumerate(extremal_posets):
        n = rec["n"]
        matrix = rec["adjacency_matrix"]
        expected_total = rec["total_extensions"]

        # 1. Verify strict partial order axioms
        assert verify_partial_order(n, matrix), f"Poset #{i} (n={n}) failed partial order axioms!"

        # 2. Count linear extensions with independent Python DFS
        total_py, pair_counts = count_linear_extensions_python(n, matrix)
        assert total_py == expected_total, f"Extension count mismatch for poset #{i}: python={total_py}, rust={expected_total}"

        # 3. Check every incomparable pair
        max_balance = Fraction(0, 1)
        incomparable_found = False

        for u in range(n):
            for v in range(u + 1, n):
                is_incomp = (matrix[u][v] == 0 and matrix[v][u] == 0)
                e_uv = pair_counts[(u, v)]
                e_vu = pair_counts[(v, u)]
                assert e_uv + e_vu == total_py, f"Pair sum violation: {e_uv} + {e_vu} != {total_py}"

                if is_incomp:
                    incomparable_found = True
                    bal = Fraction(min(e_uv, e_vu), total_py)
                    if bal > max_balance:
                        max_balance = bal

        assert incomparable_found, f"Extremal poset #{i} has no incomparable pairs!"
        assert max_balance == Fraction(1, 3), f"Extremal poset #{i} balance is {max_balance}, expected exactly 1/3!"

    print(f"ALL {len(extremal_posets)} EXTREMAL POSETS INDEPENDENTLY AUDITED AND CONFIRMED!")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        artifact_path = Path(sys.argv[1])
    else:
        artifact_path = Path(__file__).parent.parent / "data" / "frontier_results_n9.json"

    if not artifact_path.exists():
        print(f"Error: {artifact_path} does not exist.")
        sys.exit(1)
    audit_extremal_posets(artifact_path)
